name = "tycho-tools"
account_id = "845f36daec4f3cab331da0d132110613"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "tycho-tools"
database_id = "REPLACE_WITH_D1_ID"

[routes]
pattern = "tools.tycho.sh/*"
